### ISSUE TITLE
可视化部分draw_in_poincare_ball(),  Norm 运算产生0，导致除法运算报错

### ISSUE THREAD

**Issue by FUNCTIONair-han** [iMoonLab/DeepHypergraph#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2022-09-26 at 11 03 10](https://user-images.githubusercontent.com/106153416/192185766-4ea25538-b0c9-489e-897a-3bdd0a3be1fd.png)

![Screen Shot 2022-09-26 at 11 02 04](https://user-images.githubusercontent.com/106153416/192185663-473d1bbf-cc31-4f92-8a10-42acab3280b3.png)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Python: [e.g. 3.8.13]
 - PyTorch [e.g. 1.11.0]
 - DHG [e.g. 0.9.1]

**Additional context**

**Comment by yifanfeng97** [comment]
Got it!
