### ISSUE TITLE
BUG: RetrievalEvaluator.validate_add_batch use the Tensor in CPU

### ISSUE THREAD

**Issue by realxuyang** [iMoonLab/DeepHypergraph#13]
![img_v2_7d85a6be-5c10-44ad-8b89-0da26662abag](https://user-images.githubusercontent.com/45526497/192704983-9072c422-5a11-42a3-8f9f-966f0003eba9.jpg)

**Comment by yifanfeng97** [comment]
Fixed in 0.9.2!
