### ISSUE TITLE
Can the k in top-k recall (retrieval evaluator) set to a ratio of samples instead of a fixed int?

### ISSUE THREAD

**Issue by realxuyang** [iMoonLab/DeepHypergraph#14]
![img_v2_389f2482-800c-44cb-96c8-d16ef47743bg](https://user-images.githubusercontent.com/45526497/192705678-e93a17b1-cf11-4e59-86f4-cea669bb402f.jpg)

**Comment by yifanfeng97** [comment]
Yes, we already add the top ratio for `recall` metric in 0.9.2 version!
See this https://deephypergraph.readthedocs.io/en/0.9.2/api/metrics.html#dhg.metrics.retrieval.recall
