### ISSUE TITLE
BUG: hg.add_hyperedges can add edges out of vertex index

### ISSUE THREAD

**Issue by realxuyang** [iMoonLab/DeepHypergraph#15]
![img_v2_11a5a161-6140-42a5-92eb-fc68335b32ag](https://user-images.githubusercontent.com/45526497/192706763-ab3823e2-665d-402e-bc95-a621f9746751.jpg)

**Comment by yifanfeng97** [comment]
Clearly, the vertex index in your hypergraph is larger than the maximum number of vertices: 31 > num_v=21. Please check your edge_list data. 
We will add the vertex index **verification** to guarantee each vertex in hyperedge is no larger than the maximum number of vertices in the next version DHG.

**Comment by mgao97** [comment]
Could function for node type transformation, I mean ('str' -> 'int'), be added before constructing the hyperedges?

**Comment by mgao97** [comment]
> 

Looks good!  I will try to use these functions.
