### ISSUE TITLE
推荐系统指标部分出现nan，可能是由于除0导致的

### ISSUE THREAD

**Issue by jiishy** [iMoonLab/DeepHypergraph#17]
![image](https://user-images.githubusercontent.com/21833174/196373242-1da2c8b2-a45b-43a5-a98f-6c632214532b.png)

可能会影响recall指标和ndcg指标计算

<img width="710" alt="7946d8dd7a5317e810e7ccc2af5a4f4" src="https://user-images.githubusercontent.com/21833174/196380994-1a8f7b02-5010-4914-a793-9bcfec5c83cb.png">

可能需要对这一行增加判断

**Comment by yifanfeng97** [comment]
Fixed in this commit
https://github.com/iMoonLab/DeepHypergraph/commit/e124154fba503e885bd49dd8b6c6016a78fd9bbb
The next version 0.9.3 will contain this change.

**Comment by yifanfeng97** [comment]
合并到已发布的 0.9.3 https://github.com/iMoonLab/DeepHypergraph/releases/tag/v0.9.3
