### ISSUE TITLE
I am wondering if the tutorial is still going to be added? It seems like been a year for this repo.

### ISSUE THREAD

**Issue by RussellXie7** [iMoonLab/DeepHypergraph#2]

**Comment by yifanfeng97** [comment]
I will update it as soon as possible. Just after my journal finished. It
will be a big version change.

Best,
Yifan

Wanze Xie <notifications@github.com> 于2021年1月20日周三 上午6:01写道：

**Comment by yifanfeng97** [comment]
We are back with a new version DHG. Welcome to try!
