### ISSUE TITLE
Dataset: Coauthor network from DBLP 

### ISSUE THREAD

**Issue by mgao97** [iMoonLab/DeepHypergraph#21]
**Where is the dataset from? Please describe.**
It is crawled according to DBLP API with some conditions.

**Describe the dataset**
The dataset is a part of the dataset crawled according to DBLP API,  and we have selected each item based on some conditions, such as the venue and publication year (from 2018 to 2022). It contains 6498 authors and 2603 papers.

**Download link**
[Where to access the dataset. Ex. a cloud drive link or any other website.](https://drive.google.com/file/d/1g9DfcRh7KHixSN7hopL509ojaSssofVW/view?usp=sharing)

**Additional context**
Add any other context or dataset request here.

**Comment by yifanfeng97** [comment]
Got it! Thank you, we will add it in the next version this month.
谢谢你哦。我们将在这个月的下个版本DHG中添加您提供的这个数据集！

**Comment by yifanfeng97** [comment]
请问，你这个数据只有超边吗？有没有节点特征，或者节点标签之类的？

**Comment by yifanfeng97** [comment]
您好，我统计了一下，您提供的这个边表是一个长度为2603的list。我统计了一下这个list里面的所有元素的最大元素是8657，同时我也统计了一下非重复元素个数是8658，也就意味着节点的编号是一个连续的从0到8657的编号。这个是否是您说的author？想跟您再确认一下数字。

**Comment by mgao97** [comment]
是的，这个数据集还没做进一步，感谢您的考虑！


高敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iMoonLab/DeepHypergraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月15日(星期四) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iMoonLab/DeepHypergraph] Dataset: Coauthor network from DBLP  (Issue #21)





 
您好，我统计了一下，您提供的这个边表是一个长度为2603的list。我统计了一下这个list里面的所有元素的最大元素是8657，同时我也统计了一下非重复元素个数是8658，也就意味着节点的编号是一个连续的从0到8657的编号。这个是否是您说的author？想跟您再确认一下数字。

**Comment by mgao97** [comment]
是的，这个数据集可能后期会再次迭代，节点特征和label我们近期在商榷，有最新版本会再和您交流，非常感谢您的大力支持！




高敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iMoonLab/DeepHypergraph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月12日(星期一) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iMoonLab/DeepHypergraph] Dataset: Coauthor network from DBLP  (Issue #21)





 
请问，你这个数据只有超边吗？有没有节点特征，或者节点标签之类的？

**Comment by yifanfeng97** [comment]
好，那我暂定把这个归到二分图数据集类别，名字暂定 DBLPBiGraph，是否可以？

**Comment by yifanfeng97** [comment]
我现在把它分到了超图数据集，名字暂定DBLP8K可以吗？

**Comment by yifanfeng97** [comment]
0ac4fd3290504c9d4f460863c58587d6a3cb3ddc

**Comment by mgao97** [comment]
收到，可以的，感谢支持



---Original---
From: "Yifan ***@***.***&gt;
Date: Fri, Dec 16, 2022 11:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [iMoonLab/DeepHypergraph] Dataset: Coauthor network from DBLP (Issue #21)




 
我现在把它分到了超图数据集，名字暂定DBLP8K可以吗？

**Comment by yifanfeng97** [comment]
已合并到 https://github.com/iMoonLab/DeepHypergraph/releases/tag/v0.9.3
