### ISSUE TITLE
hypergraph.e2v_aggregation_of_group方法出错

### ISSUE THREAD

**Issue by tsubasa0425** [iMoonLab/DeepHypergraph#22]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/55352211/202973271-eb2f43f9-9d68-49b8-aa18-f1d791779ad8.png">
好像要改成 `self.D_v_neg_1_of_group(group_name)` ？

**Comment by yifanfeng97** [comment]
是的！
谢谢你，俺这就改！

**Comment by yifanfeng97** [comment]
fix it in commit bd8a8dd5c27f5493fe928737be272b1ae15eab99 .
