### ISSUE TITLE
Unable to install dhg using pip

### ISSUE THREAD

**Issue by flash-barry** [iMoonLab/DeepHypergraph#35]
When I install this package, the following error occurs.
![e5e4ac5cbc7d03ac3c9d998b7566a7ce](https://user-images.githubusercontent.com/49780249/232988228-f1d26f54-fbd7-40b2-8aba-2a22e12f1260.png)

**Comment by yifanfeng97** [comment]
![image](https://user-images.githubusercontent.com/15007108/233793491-876c8c7e-3b50-4826-a910-7b1895c93bd6.png)
I have tested it in Windows and Linux. just use the following commands

1. conda create -n dhg python=3.8
2. pip install dhg

**Comment by flash-barry** [comment]
Problem solved, thx
