### ISSUE TITLE
使用GAT需要调用Graph类v2v中x=torch.sparse.mm(P,dim=1)，这里应该是x=torch.sparse.softmax(P,dim=1)

### ISSUE THREAD

**Issue by FuYou0723** [iMoonLab/DeepHypergraph#43]

**Comment by yifanfeng97** [comment]
Following up on this issue — the fix applied when this was closed was only partial.

The `torch.sparse.mm(P, dim=1)` → `torch.sparse.softmax(P, dim=1)` fix was applied to the **`e_weight` branch** (the code path when a custom `e_weight` is passed to `v2v`), but the **default branch** (when `e_weight` is `None`) was left unchanged and still contained the buggy call.

This means `g.v2v(X, aggr="softmax_then_sum")` without a custom `e_weight` would still raise `TypeError`. The default branch (`graph.py:680`) has now been fixed as well.
