### ISSUE TITLE
Optuna version 1.10 is not exist

### ISSUE THREAD

**Issue by mamintoosi** [iMoonLab/DeepHypergraph#7]
**Describe the bug**
During installation, I got an error related to optuna package: optuna<2 and >=1.10 is required, but optuna has not version number equal 1.10, the next version after 1.5, is 2.x.

**Environment (please complete the following information):**
 - Python: [3.8.1]
 - PyTorch [1.12.1]
 - DHG [0.9.0]

**Additional context**
By modifying pyproject.toml and changed optuna requirements to 
optuna = "^1.5"
the problem is solved

**Comment by yifanfeng97** [comment]
Thanks. We will fix this.
